services:
  hh-php:
    container_name: hh-php
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./../:/var/www/

  hh-nginx:
    container_name: hh-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - hh-php